export const CartActionTypes = {
  TOGGLE_CART_DIALOG_VISIBILITY: "TOGGLE_CART_DIALOG_VISIBILITY",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  CLEAR_CART: "CLEAR_CART",
};
